### ISSUE TITLE
Refactor of unused code

### ISSUE THREAD

**Issue by montaguehb** [montaguehb/phase-4-full-stack-project#126]

**Comment by nolannash** [comment]
Places with refactors im not 100% about:

- ConcertPage.py --> line 2 --> import path for react router dom looks questionable

- Login.js --> line 9 && line 10 --> updateLogin never used, history never used

- Profile.js --> line 35 --> random open close html tags

- SignUp.js --> line 9 --> history is never used

- index.js --> lines 12+18 && lines 21-24 --> are we leaving strict mode on? Do we need the reportWebVitals()

- config.py --> line 12 --> are we gonna do anything about our super secret secret key?

- models.py --> user class has commented out "serialize rules" do we need?

- seed.py --> line 2 --> import tempfile ? needed
